"""Train a separated decision receiver from an information-closed MPC label.

The label is generated by querying the cognitive dynamics model over a small
action grid and minimizing a state cost.  It therefore does not read hidden
factor labels; the decision network can only use information available through
the cognitive interface.
"""

from __future__ import annotations

import argparse
import json

import torch
import torch.nn.functional as F

from physics_transfer.multifactor_data import sample_multifactor_batch
from physics_transfer.separated_decision import SeparatedPhysicsDecision
from scripts.stage2_lowrank_gap_calibration import FACTORS, HELDOUT, _pair
from scripts.stage2_lowrank_semantic import train as train_cognitive


ACTIONS = torch.linspace(-1.0, 1.0, 9)


def state_cost(state):
    """Smooth upright-and-low-speed proxy; no hidden physical factor needed."""
    return (
        0.5 * state[:, 4].square() + 0.5 * state[:, 5].square()
        + 0.5 * (1.0 - state[:, 0]) + 0.25 * (1.0 - state[:, 2])
    )


def cognitive_code(cognitive, batch):
    with torch.no_grad():
        return cognitive(batch["history"], batch["state"], batch["action"])["physics_coefficients"]


def information_closed_target(cognitive, batch):
    """Return a discrete action selected only through cognitive predictions."""
    actions = ACTIONS.to(batch["state"].device).view(1, -1, 1).expand(batch["state"].shape[0], -1, -1)
    state = batch["state"][:, None, :].expand(-1, actions.shape[1], -1).reshape(-1, batch["state"].shape[-1])
    history = batch["history"][:, None, :].expand(-1, actions.shape[1], -1).reshape(-1, batch["history"].shape[-1])
    action = actions.reshape(-1, 1)
    with torch.no_grad():
        prediction = cognitive(history, state, action)["next_state"]
    costs = state_cost(prediction).view(batch["state"].shape[0], -1)
    index = costs.argmin(dim=1)
    return actions[:, :, 0].gather(1, index[:, None]), cognitive_code(cognitive, batch)


def train_receiver(cognitive, steps, seed):
    torch.manual_seed(seed + 12000)
    receiver = SeparatedPhysicsDecision(6, 1, 4, hidden_dim=24, n_prototypes=8)
    optimizer = torch.optim.Adam(receiver.parameters(), lr=2e-3)
    for _ in range(steps):
        batch = sample_multifactor_batch(64, 8, FACTORS)
        target, code = information_closed_target(cognitive, batch)
        prediction = receiver(batch["state"], code)["action"]
        loss = F.mse_loss(prediction, target)
        optimizer.zero_grad(); loss.backward(); torch.nn.utils.clip_grad_norm_(receiver.parameters(), 5.0); optimizer.step()
    return receiver


def evaluate(cognitive, receiver):
    receiver.eval()
    with torch.no_grad():
        batch = sample_multifactor_batch(1024, 8, HELDOUT)
        target, code = information_closed_target(cognitive, batch)
        prediction = receiver(batch["state"], code)["action"]
        shuffled = receiver(batch["state"], code[torch.randperm(1024)])["action"]
        return {"teacher_mse": F.mse_loss(prediction, target).item(), "shuffle_delta": F.mse_loss(shuffled, target).item() - F.mse_loss(prediction, target).item(), "teacher_action_std": target.std().item()}


def main():
    parser = argparse.ArgumentParser(); parser.add_argument("--cognitive-steps", type=int, default=300); parser.add_argument("--decision-steps", type=int, default=300); parser.add_argument("--seed", type=int, default=42); args = parser.parse_args()
    cognitive = train_cognitive(0.1, args.cognitive_steps, args.seed); cognitive.eval()
    receiver = train_receiver(cognitive, args.decision_steps, args.seed)
    print(json.dumps(evaluate(cognitive, receiver), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
